import os

pa_spec = {
        'train_scp': 'data/spec/PA_train/feats_slicing.scp',
        'train_utt2index': 'data/spec/PA_train/utt2index',
        'dev_scp': 'data/spec/PA_dev/feats_slicing.scp',
        'dev_utt2index': 'data/spec/PA_dev/utt2index',
        'dev_utt2systemID': 'data/spec/PA_dev/utt2systemID',
        'scoring_dir': 'scoring/pa_cm_scores/',
        'eval_scp': 'data/spec/PA_eval/feats_slicing.scp',
        'eval_utt2index': 'data/spec/PA_eval/utt2index',
        'eval_utt2systemID': 'data/spec/PA_eval/utt2systemID',
        'eval_19_scp': 'data/spec/PA_eval_19/feats_slicing.scp',
        'eval_19_utt2index': 'data/spec/PA_eval_19/utt2index',
        'eval_19_utt2systemID': 'data/spec/PA_eval_19/utt2systemID',
        'isstft': False,
}

pa_lfcc = {
        'train_scp': 'data/lfcc/PA_train/feats_slicing.scp',
        'train_utt2index': 'data/lfcc/PA_train/utt2index',
        'dev_scp': 'data/lfcc/PA_dev/feats_slicing.scp',
        'dev_utt2index': 'data/lfcc/PA_dev/utt2index',
        'dev_utt2systemID': 'data/lfcc/PA_dev/utt2systemID',
        'scoring_dir': 'scoring/pa_cm_scores/',
        'eval_scp': 'data/lfcc/PA_eval/feats_slicing.scp',
        'eval_utt2index': 'data/lfcc/PA_eval/utt2index',
        'eval_utt2systemID': 'data/lfcc/PA_eval/utt2systemID',
        'eval_19_scp': 'data/lfcc/PA_eval_19/feats_slicing.scp',
        'eval_19_utt2index': 'data/lfcc/PA_eval_19/utt2index',
        'eval_19_utt2systemID': 'data/lfcc/PA_eval_19/utt2systemID',
        'isstft': False,
}

pa_cqt = {
        'train_scp': 'data/cqt/PA_train/feats_slicing.scp',
        'train_utt2index': 'data/cqt/PA_train/utt2index',
        'dev_scp': 'data/cqt/PA_dev/feats_slicing.scp',
        'dev_utt2index': 'data/cqt/PA_dev/utt2index',
        'dev_utt2systemID': 'data/cqt/PA_dev/utt2systemID',
        'scoring_dir': 'scoring/pa_cm_scores/',
        'eval_scp': 'data/cqt/PA_eval/feats_slicing.scp',
        'eval_utt2index': 'data/cqt/PA_eval/utt2index',
        'eval_utt2systemID': 'data/cqt/PA_eval/utt2systemID',
        'eval_19_scp': 'data/cqt/PA_eval_19/feats_slicing.scp',
        'eval_19_utt2index': 'data/cqt/PA_eval_19/utt2index',
        'eval_19_utt2systemID': 'data/cqt/PA_eval_19/utt2systemID',
        'isstft': False,
}

la_spec = {
        'train_scp': 'data/spec/LA_train/feats_slicing.scp',
        'train_utt2index': 'data/spec/LA_train/utt2index',
        'dev_scp': 'data/spec/LA_dev/feats_slicing.scp',
        'dev_utt2index': 'data/spec/LA_dev/utt2index',
        'dev_utt2systemID': 'data/spec/LA_dev/utt2systemID',
        'scoring_dir': 'scoring/la_cm_scores/',
        'eval_scp': 'data/spec/LA_eval/feats_slicing.scp',
        'eval_utt2index': 'data/spec/LA_eval/utt2index',
        'eval_utt2systemID': 'data/spec/LA_eval/utt2systemID',
        'eval_19_scp': 'data/spec/LA_eval_19/feats_slicing.scp',
        'eval_19_utt2index': 'data/spec/LA_eval_19/utt2index',
        'eval_19_utt2systemID': 'data/spec/LA_eval_19/utt2systemID',
        'isstft': False,
}

la_lfccori = {
        'train_scp': 'data/lfccori/LA_train/feats_slicing.scp',
        'train_utt2index': 'data/lfccori/LA_train/utt2index',
        'dev_scp': 'data/lfccori/LA_dev/feats_slicing.scp',
        'dev_utt2index': 'data/lfccori/LA_dev/utt2index',
        'dev_utt2systemID': 'data/lfccori/LA_dev/utt2systemID',
        'scoring_dir': 'scoring/la_cm_scores/',
        'eval_scp': 'data/lfccori/LA_eval/feats_slicing.scp',
        'eval_utt2index': 'data/lfccori/LA_eval/utt2index',
        'eval_utt2systemID': 'data/lfccori/LA_eval/utt2systemID',
        'eval_19_scp': 'data/lfccori/LA_eval_19/feats_slicing.scp',
        'eval_19_utt2index': 'data/lfccori/LA_eval_19/utt2index',
        'eval_19_utt2systemID': 'data/lfccori/LA_eval_19/utt2systemID',
        'isstft': False,
}

la_lfcc = {
        'train_scp': 'data/lfcc/LA_train/feats_slicing.scp',
        'train_utt2index': 'data/lfcc/LA_train/utt2index',
        'dev_scp': 'data/lfcc/LA_dev/feats_slicing.scp',
        'dev_utt2index': 'data/lfcc/LA_dev/utt2index',
        'dev_utt2systemID': 'data/lfcc/LA_dev/utt2systemID',
        'scoring_dir': 'scoring/la_cm_scores/',
        'eval_scp': 'data/lfcc/LA_eval/feats_slicing.scp',
        'eval_utt2index': 'data/lfcc/LA_eval/utt2index',
        'eval_utt2systemID': 'data/lfcc/LA_eval/utt2systemID',
        'eval_19_scp': 'data/lfcc/LA_eval_19/feats_slicing.scp',
        'eval_19_utt2index': 'data/lfcc/LA_eval_19/utt2index',
        'eval_19_utt2systemID': 'data/lfcc/LA_eval_19/utt2systemID',
        'isstft': False,
}

laaugalaw_cqt = {
        'train_scp': 'data/cqt/LAaugalaw_train/feats_slicing.scp',
        'train_utt2index': 'data/cqt/LAaugalaw_train/utt2index',
        'dev_scp': 'data/cqt/LAaugalaw_dev/feats_slicing.scp',
        'dev_utt2index': 'data/cqt/LAaugalaw_dev/utt2index',
        'dev_utt2systemID': 'data/cqt/LAaugalaw_dev/utt2systemID',
        'scoring_dir': 'scoring/laaugalaw_cm_scores/',
        'eval_scp': 'data/cqt/LA_eval/feats_slicing.scp',
        'eval_utt2index': 'data/cqt/LA_eval/utt2index',
        'eval_utt2systemID': 'data/cqt/LA_eval/utt2systemID',
        'eval_19_scp': 'data/cqt/LA_eval_19/feats_slicing.scp',
        'eval_19_utt2index': 'data/cqt/LA_eval_19/utt2index',
        'eval_19_utt2systemID': 'data/cqt/LA_eval_19/utt2systemID',
        'eval_df_scp': 'data/cqt/DF_eval/feats_slicing.scp',
        'eval_df_utt2index': 'data/cqt/DF_eval/utt2index',
        'eval_df_utt2systemID': 'data/cqt/DF_eval/utt2systemID',
        'isstft': False,
}

laaugg726_cqt = {
        'train_scp': 'data/cqt/LAaugg726_train/feats_slicing.scp',
        'train_utt2index': 'data/cqt/LAaugg726_train/utt2index',
        'dev_scp': 'data/cqt/LAaugg726_dev/feats_slicing.scp',
        'dev_utt2index': 'data/cqt/LAaugg726_dev/utt2index',
        'dev_utt2systemID': 'data/cqt/LAaugg726_dev/utt2systemID',
        'scoring_dir': 'scoring/laaugg726_cm_scores/',
        'eval_scp': 'data/cqt/LA_eval/feats_slicing.scp',
        'eval_utt2index': 'data/cqt/LA_eval/utt2index',
        'eval_utt2systemID': 'data/cqt/LA_eval/utt2systemID',
        'eval_19_scp': 'data/cqt/LA_eval_19/feats_slicing.scp',
        'eval_19_utt2index': 'data/cqt/LA_eval_19/utt2index',
        'eval_19_utt2systemID': 'data/cqt/LA_eval_19/utt2systemID',
        'eval_df_scp': 'data/cqt/DF_eval/feats_slicing.scp',
        'eval_df_utt2index': 'data/cqt/DF_eval/utt2index',
        'eval_df_utt2systemID': 'data/cqt/DF_eval/utt2systemID',
        'isstft': False,
}

laaugg711g726mbrg722mbr_cqt = {
        'train_scp': 'data/cqt/LAaugg711g726mbrg722mbr_train/feats_slicing.scp',
        'train_utt2index': 'data/cqt/LAaugg711g726mbrg722mbr_train/utt2index',
        'dev_scp': 'data/cqt/LAaugg711g726mbrg722mbr_dev/feats_slicing.scp',
        'dev_utt2index': 'data/cqt/LAaugg711g726mbrg722mbr_dev/utt2index',
        'dev_utt2systemID': 'data/cqt/LAaugg711g726mbrg722mbr_dev/utt2systemID',
        'scoring_dir': 'scoring/laaugg711g726mbrg722mbr_cm_scores/',
        'eval_scp': 'data/cqt/LA_eval/feats_slicing.scp',
        'eval_utt2index': 'data/cqt/LA_eval/utt2index',
        'eval_utt2systemID': 'data/cqt/LA_eval/utt2systemID',
        'eval_19_scp': 'data/cqt/LA_eval_19/feats_slicing.scp',
        'eval_19_utt2index': 'data/cqt/LA_eval_19/utt2index',
        'eval_19_utt2systemID': 'data/cqt/LA_eval_19/utt2systemID',
        'eval_df_scp': 'data/cqt/DF_eval/feats_slicing.scp',
        'eval_df_utt2index': 'data/cqt/DF_eval/utt2index',
        'eval_df_utt2systemID': 'data/cqt/DF_eval/utt2systemID',
        'isstft': False,
}

laaugmp3m4ag726mbrg711g722mbr_cqt = {
        'train_scp': 'data/cqt/LAaugmp3m4ag726mbrg711g722mbr_train/feats_slicing.scp',
        'train_utt2index': 'data/cqt/LAaugmp3m4ag726mbrg711g722mbr_train/utt2index',
        'dev_scp': 'data/cqt/LAaugmp3m4ag726mbrg711g722mbr_dev/feats_slicing.scp',
        'dev_utt2index': 'data/cqt/LAaugmp3m4ag726mbrg711g722mbr_dev/utt2index',
        'dev_utt2systemID': 'data/cqt/LAaugmp3m4ag726mbrg711g722mbr_dev/utt2systemID',
        'scoring_dir': 'scoring/laaugmp3m4ag726mbrg711g722mbr_cm_scores/',
        'eval_scp': 'data/cqt/LA_eval/feats_slicing.scp',
        'eval_utt2index': 'data/cqt/LA_eval/utt2index',
        'eval_utt2systemID': 'data/cqt/LA_eval/utt2systemID',
        'eval_19_scp': 'data/cqt/LA_eval_19/feats_slicing.scp',
        'eval_19_utt2index': 'data/cqt/LA_eval_19/utt2index',
        'eval_19_utt2systemID': 'data/cqt/LA_eval_19/utt2systemID',
        'eval_df_scp': 'data/cqt/DF_eval/feats_slicing.scp',
        'eval_df_utt2index': 'data/cqt/DF_eval/utt2index',
        'eval_df_utt2systemID': 'data/cqt/DF_eval/utt2systemID',
        'isstft': False,
}

laaugg722_cqt = {
        'train_scp': 'data/cqt/LAaugg722_train/feats_slicing.scp',
        'train_utt2index': 'data/cqt/LAaugg722_train/utt2index',
        'dev_scp': 'data/cqt/LAaugg722_dev/feats_slicing.scp',
        'dev_utt2index': 'data/cqt/LAaugg722_dev/utt2index',
        'dev_utt2systemID': 'data/cqt/LAaugg722_dev/utt2systemID',
        'scoring_dir': 'scoring/laaugg722_cm_scores/',
        'eval_scp': 'data/cqt/LA_eval/feats_slicing.scp',
        'eval_utt2index': 'data/cqt/LA_eval/utt2index',
        'eval_utt2systemID': 'data/cqt/LA_eval/utt2systemID',
        'eval_19_scp': 'data/cqt/LA_eval_19/feats_slicing.scp',
        'eval_19_utt2index': 'data/cqt/LA_eval_19/utt2index',
        'eval_19_utt2systemID': 'data/cqt/LA_eval_19/utt2systemID',
        'eval_df_scp': 'data/cqt/DF_eval/feats_slicing.scp',
        'eval_df_utt2index': 'data/cqt/DF_eval/utt2index',
        'eval_df_utt2systemID': 'data/cqt/DF_eval/utt2systemID',
        'isstft': False,
}

laaugulaw_cqt = {
        'train_scp': 'data/cqt/LAaugulaw_train/feats_slicing.scp',
        'train_utt2index': 'data/cqt/LAaugulaw_train/utt2index',
        'dev_scp': 'data/cqt/LAaugulaw_dev/feats_slicing.scp',
        'dev_utt2index': 'data/cqt/LAaugulaw_dev/utt2index',
        'dev_utt2systemID': 'data/cqt/LAaugulaw_dev/utt2systemID',
        'scoring_dir': 'scoring/laaugulaw_cm_scores/',
        'eval_scp': 'data/cqt/LA_eval/feats_slicing.scp',
        'eval_utt2index': 'data/cqt/LA_eval/utt2index',
        'eval_utt2systemID': 'data/cqt/LA_eval/utt2systemID',
        'eval_19_scp': 'data/cqt/LA_eval_19/feats_slicing.scp',
        'eval_19_utt2index': 'data/cqt/LA_eval_19/utt2index',
        'eval_19_utt2systemID': 'data/cqt/LA_eval_19/utt2systemID',
        'eval_df_scp': 'data/cqt/DF_eval/feats_slicing.scp',
        'eval_df_utt2index': 'data/cqt/DF_eval/utt2index',
        'eval_df_utt2systemID': 'data/cqt/DF_eval/utt2systemID',
        'isstft': False,
}

laaugg711_cqt = {
        'train_scp': 'data/cqt/LAaugg711_train/feats_slicing.scp',
        'train_utt2index': 'data/cqt/LAaugg711_train/utt2index',
        'dev_scp': 'data/cqt/LAaugg711_dev/feats_slicing.scp',
        'dev_utt2index': 'data/cqt/LAaugg711_dev/utt2index',
        'dev_utt2systemID': 'data/cqt/LAaugg711_dev/utt2systemID',
        'scoring_dir': 'scoring/laaugg711_cm_scores/',
        'eval_scp': 'data/cqt/LA_eval/feats_slicing.scp',
        'eval_utt2index': 'data/cqt/LA_eval/utt2index',
        'eval_utt2systemID': 'data/cqt/LA_eval/utt2systemID',
        'eval_19_scp': 'data/cqt/LA_eval_19/feats_slicing.scp',
        'eval_19_utt2index': 'data/cqt/LA_eval_19/utt2index',
        'eval_19_utt2systemID': 'data/cqt/LA_eval_19/utt2systemID',
        'eval_df_scp': 'data/cqt/DF_eval/feats_slicing.scp',
        'eval_df_utt2index': 'data/cqt/DF_eval/utt2index',
        'eval_df_utt2systemID': 'data/cqt/DF_eval/utt2systemID',
        'isstft': False,
}

laaugg726mbr_cqt = {
        'train_scp': 'data/cqt/LAaugg726mbr_train/feats_slicing.scp',
        'train_utt2index': 'data/cqt/LAaugg726mbr_train/utt2index',
        'dev_scp': 'data/cqt/LAaugg726mbr_dev/feats_slicing.scp',
        'dev_utt2index': 'data/cqt/LAaugg726mbr_dev/utt2index',
        'dev_utt2systemID': 'data/cqt/LAaugg726mbr_dev/utt2systemID',
        'scoring_dir': 'scoring/laaugg726mbr_cm_scores/',
        'eval_scp': 'data/cqt/LA_eval/feats_slicing.scp',
        'eval_utt2index': 'data/cqt/LA_eval/utt2index',
        'eval_utt2systemID': 'data/cqt/LA_eval/utt2systemID',
        'eval_19_scp': 'data/cqt/LA_eval_19/feats_slicing.scp',
        'eval_19_utt2index': 'data/cqt/LA_eval_19/utt2index',
        'eval_19_utt2systemID': 'data/cqt/LA_eval_19/utt2systemID',
        'eval_df_scp': 'data/cqt/DF_eval/feats_slicing.scp',
        'eval_df_utt2index': 'data/cqt/DF_eval/utt2index',
        'eval_df_utt2systemID': 'data/cqt/DF_eval/utt2systemID',
        'isstft': False,
}

laaugg722mbr_cqt = {
        'train_scp': 'data/cqt/LAaugg722mbr_train/feats_slicing.scp',
        'train_utt2index': 'data/cqt/LAaugg722mbr_train/utt2index',
        'dev_scp': 'data/cqt/LAaugg722mbr_dev/feats_slicing.scp',
        'dev_utt2index': 'data/cqt/LAaugg722mbr_dev/utt2index',
        'dev_utt2systemID': 'data/cqt/LAaugg722mbr_dev/utt2systemID',
        'scoring_dir': 'scoring/laaugg722mbr_cm_scores/',
        'eval_scp': 'data/cqt/LA_eval/feats_slicing.scp',
        'eval_utt2index': 'data/cqt/LA_eval/utt2index',
        'eval_utt2systemID': 'data/cqt/LA_eval/utt2systemID',
        'eval_19_scp': 'data/cqt/LA_eval_19/feats_slicing.scp',
        'eval_19_utt2index': 'data/cqt/LA_eval_19/utt2index',
        'eval_19_utt2systemID': 'data/cqt/LA_eval_19/utt2systemID',
        'eval_df_scp': 'data/cqt/DF_eval/feats_slicing.scp',
        'eval_df_utt2index': 'data/cqt/DF_eval/utt2index',
        'eval_df_utt2systemID': 'data/cqt/DF_eval/utt2systemID',
        'isstft': False,
}

laaugmp3m4a_cqt = {
        'train_scp': 'data/cqt/LAaugmp3m4a_train/feats_slicing.scp',
        'train_utt2index': 'data/cqt/LAaugmp3m4a_train/utt2index',
        'dev_scp': 'data/cqt/LAaugmp3m4a_dev/feats_slicing.scp',
        'dev_utt2index': 'data/cqt/LAaugmp3m4a_dev/utt2index',
        'dev_utt2systemID': 'data/cqt/LAaugmp3m4a_dev/utt2systemID',
        'scoring_dir': 'scoring/laaugmp3m4a_cm_scores/',
        'eval_scp': 'data/cqt/LA_eval/feats_slicing.scp',
        'eval_utt2index': 'data/cqt/LA_eval/utt2index',
        'eval_utt2systemID': 'data/cqt/LA_eval/utt2systemID',
        'eval_19_scp': 'data/cqt/LA_eval_19/feats_slicing.scp',
        'eval_19_utt2index': 'data/cqt/LA_eval_19/utt2index',
        'eval_19_utt2systemID': 'data/cqt/LA_eval_19/utt2systemID',
        'eval_df_scp': 'data/cqt/DF_eval/feats_slicing.scp',
        'eval_df_utt2index': 'data/cqt/DF_eval/utt2index',
        'eval_df_utt2systemID': 'data/cqt/DF_eval/utt2systemID',
        'isstft': False,
}

laalawg722_cqt = {
        'train_scp': 'data/cqt/LAalawg722_train/feats_slicing.scp',
        'train_utt2index': 'data/cqt/LAalawg722_train/utt2index',
        'dev_scp': 'data/cqt/LAalawg722_dev/feats_slicing.scp',
        'dev_utt2index': 'data/cqt/LAalawg722_dev/utt2index',
        'dev_utt2systemID': 'data/cqt/LAalawg722_dev/utt2systemID',
        'scoring_dir': 'scoring/laalawg722_cm_scores/',
        'eval_scp': 'data/cqt/LA_eval/feats_slicing.scp',
        'eval_utt2index': 'data/cqt/LA_eval/utt2index',
        'eval_utt2systemID': 'data/cqt/LA_eval/utt2systemID',
        'eval_19_scp': 'data/cqt/LA_eval_19/feats_slicing.scp',
        'eval_19_utt2index': 'data/cqt/LA_eval_19/utt2index',
        'eval_19_utt2systemID': 'data/cqt/LA_eval_19/utt2systemID',
        'eval_df_scp': 'data/cqt/DF_eval/feats_slicing.scp',
        'eval_df_utt2index': 'data/cqt/DF_eval/utt2index',
        'eval_df_utt2systemID': 'data/cqt/DF_eval/utt2systemID',
        'isstft': False,
}

laaug_lfccori = {
        'train_scp': 'data/lfccori/LAaug_train/feats_slicing.scp',
        'train_utt2index': 'data/lfccori/LAaug_train/utt2index',
        'dev_scp': 'data/lfccori/LAaug_dev/feats_slicing.scp',
        'dev_utt2index': 'data/lfccori/LAaug_dev/utt2index',
        'dev_utt2systemID': 'data/lfccori/LAaug_dev/utt2systemID',
        'scoring_dir': 'scoring/laaug_cm_scores/',
        'eval_scp': 'data/lfccori/LA_eval/feats_slicing.scp',
        'eval_utt2index': 'data/lfccori/LA_eval/utt2index',
        'eval_utt2systemID': 'data/lfccori/LA_eval/utt2systemID',
        'eval_19_scp': 'data/lfccori/LA_eval_19/feats_slicing.scp',
        'eval_19_utt2index': 'data/lfccori/LA_eval_19/utt2index',
        'eval_19_utt2systemID': 'data/lfccori/LA_eval_19/utt2systemID',
        'isstft': False,
}

laaugmp3m4ag726mbr_cqt = {
        'train_scp': 'data/cqt/LAaugmp3m4ag726mbr_train/feats_slicing.scp',
        'train_utt2index': 'data/cqt/LAaugmp3m4ag726mbr_train/utt2index',
        'dev_scp': 'data/cqt/LAaugmp3m4ag726mbr_dev/feats_slicing.scp',
        'dev_utt2index': 'data/cqt/LAaugmp3m4ag726mbr_dev/utt2index',
        'dev_utt2systemID': 'data/cqt/LAaugmp3m4ag726mbr_dev/utt2systemID',
        'scoring_dir': 'scoring/laaugmp3m4ag726mbr_cm_scores/',
        'eval_scp': 'data/cqt/LA_eval/feats_slicing.scp',
        'eval_utt2index': 'data/cqt/LA_eval/utt2index',
        'eval_utt2systemID': 'data/cqt/LA_eval/utt2systemID',
        'eval_19_scp': 'data/cqt/LA_eval_19/feats_slicing.scp',
        'eval_19_utt2index': 'data/cqt/LA_eval_19/utt2index',
        'eval_19_utt2systemID': 'data/cqt/LA_eval_19/utt2systemID',
        'eval_df_scp': 'data/cqt/DF_eval/feats_slicing.scp',
        'eval_df_utt2index': 'data/cqt/DF_eval/utt2index',
        'eval_df_utt2systemID': 'data/cqt/DF_eval/utt2systemID',
        'isstft': False,
}

laaug_cqt = {
        'train_scp': 'data/cqt/LAaug_train/feats_slicing.scp',
        'train_utt2index': 'data/cqt/LAaug_train/utt2index',
        'dev_scp': 'data/cqt/LAaug_dev/feats_slicing.scp',
        'dev_utt2index': 'data/cqt/LAaug_dev/utt2index',
        'dev_utt2systemID': 'data/cqt/LAaug_dev/utt2systemID',
        'scoring_dir': 'scoring/laaug_cm_scores/',
        'eval_scp': 'data/cqt/LA_eval/feats_slicing.scp',
        'eval_utt2index': 'data/cqt/LA_eval/utt2index',
        'eval_utt2systemID': 'data/cqt/LA_eval/utt2systemID',
        'eval_19_scp': 'data/cqt/LA_eval_19/feats_slicing.scp',
        'eval_19_utt2index': 'data/cqt/LA_eval_19/utt2index',
        'eval_19_utt2systemID': 'data/cqt/LA_eval_19/utt2systemID',
        'eval_df_scp': 'data/cqt/DF_eval/feats_slicing.scp',
        'eval_df_utt2index': 'data/cqt/DF_eval/utt2index',
        'eval_df_utt2systemID': 'data/cqt/DF_eval/utt2systemID',
        'isstft': False,
}

la_cqt = {
        'train_scp': 'data/cqt/LA_train/feats_slicing.scp',
        'train_utt2index': 'data/cqt/LA_train/utt2index',
        'dev_scp': 'data/cqt/LA_dev/feats_slicing.scp',
        'dev_utt2index': 'data/cqt/LA_dev/utt2index',
        'dev_utt2systemID': 'data/cqt/LA_dev/utt2systemID',
        'scoring_dir': 'scoring/la_cm_scores/',
        'eval_scp': 'data/cqt/LA_eval/feats_slicing.scp',
        'eval_utt2index': 'data/cqt/LA_eval/utt2index',
        'eval_utt2systemID': 'data/cqt/LA_eval/utt2systemID',
        'eval_19_scp': 'data/cqt/LA_eval_19/feats_slicing.scp',
        'eval_19_utt2index': 'data/cqt/LA_eval_19/utt2index',
        'eval_19_utt2systemID': 'data/cqt/LA_eval_19/utt2systemID',
        'eval_df_scp': 'data/cqt/DF_eval/feats_slicing.scp',
        'eval_df_utt2index': 'data/cqt/DF_eval/utt2index',
        'eval_df_utt2systemID': 'data/cqt/DF_eval/utt2systemID',
        'isstft': False,
}

la_stft = {
        'train_scp': 'data/stft/LA_train/feats_slicing.scp',
        'train_utt2index': 'data/stft/LA_train/utt2index',
        'dev_scp': 'data/stft/LA_dev/feats_slicing.scp',
        'dev_utt2index': 'data/stft/LA_dev/utt2index',
        'dev_utt2systemID': 'data/stft/LA_dev/utt2systemID',
        'scoring_dir': 'scoring/la_cm_scores/',
        'eval_scp': 'data/stft/LA_eval/feats_slicing.scp',
        'eval_utt2index': 'data/stft/LA_eval/utt2index',
        'eval_utt2systemID': 'data/stft/LA_eval/utt2systemID',
        'eval_19_scp': 'data/stft/LA_eval_19/feats_slicing.scp',
        'eval_19_utt2index': 'data/stft/LA_eval_19/utt2index',
        'eval_19_utt2systemID': 'data/stft/LA_eval_19/utt2systemID',
        'isstft': True,
}

df_cqt = {
        'train_scp': 'data/cqt/LA_train/feats_slicing.scp',
        'train_utt2index': 'data/cqt/LA_train/utt2index',
        'dev_scp': 'data/cqt/LA_dev/feats_slicing.scp',
        'dev_utt2index': 'data/cqt/LA_dev/utt2index',
        'dev_utt2systemID': 'data/cqt/LA_dev/utt2systemID',
        'scoring_dir': 'scoring/df_cm_scores/',
        'eval_scp': 'data/cqt/DF_eval/feats_slicing.scp',
        'eval_utt2index': 'data/cqt/DF_eval/utt2index',
        'eval_utt2systemID': 'data/cqt/DF_eval/utt2systemID',
        'eval_19_scp': 'data/cqt/LA_eval_19/feats_slicing.scp',
        'eval_19_utt2index': 'data/cqt/LA_eval_19/utt2index',
        'eval_19_utt2systemID': 'data/cqt/LA_eval_19/utt2systemID',
        'isstft': False,
}

debug_feats = {
        'train_scp': 'data/debug_samples/feats_slicing.scp',
        'train_utt2index': 'data/debug_samples/utt2index',
        'dev_scp': 'data/debug_samples/feats_slicing.scp',
        'dev_utt2index': 'data/debug_samples/utt2index',
        'dev_utt2systemID': 'data/debug_samples/utt2systemID',
        'scoring_dir': 'scoring/cm_scores/',
        'eval_scp': 'data/debug_samples/feats_slicing.scp',
        'eval_utt2index': 'data/debug_samples/utt2index',
        'eval_utt2systemID': 'data/debug_samples/utt2systemID', 
        'isstft': False,
}

data_prepare = {
        'pa_spec': pa_spec,
        'pa_cqt': pa_cqt,
        'pa_lfcc': pa_lfcc,
        'la_spec': la_spec,
        'la_cqt': la_cqt,
        'la_lfcc': la_lfcc,
        'la_lfccori': la_lfccori,
        'la_stft': la_stft,
        'laaug_cqt': laaug_cqt,
        'laaugmp3m4ag726mbr_cqt': laaugmp3m4ag726mbr_cqt,
        'laaugg711g726mbrg722mbr_cqt': laaugg711g726mbrg722mbr_cqt,
        'laaugmp3m4ag726mbrg711g722mbr_cqt': laaugmp3m4ag726mbrg711g722mbr_cqt,
        'laaug_lfccori': laaug_lfccori,
        'laalawg722_cqt': laalawg722_cqt,
        'laaugalaw_cqt': laaugalaw_cqt,
        'laaugg722_cqt': laaugg722_cqt,
        'laaugg726_cqt': laaugg726_cqt,
        'laaugulaw_cqt': laaugulaw_cqt,
        'laaugg711_cqt': laaugg711_cqt,
        'laaugg722mbr_cqt': laaugg722mbr_cqt,
        'laaugg726mbr_cqt': laaugg726mbr_cqt,
        'laaugmp3m4a_cqt': laaugmp3m4a_cqt,
        'df_cqt': df_cqt,
        'debug_feats': debug_feats,
}

